[package]
name = "simple_status"
version = "0.1.1"
edition = "2021"

[dependencies]
x11 = "2.19.1"
chrono = "0.4.19"
sysinfo = "0.22.5"
serde = "1.0.133"
serde_derive = "1.0.133"
serde_yaml = "0.8.23"
home = "0.5.3"
