[package]
name = "simple_status"
version = "0.1.0"
edition = "2021"

[dependencies]
x11 = "2.19.1"
chrono = "0.4.19"
sysinfo = "0.22.5"
toml = "0.5.8"
serde = "1.0.133"
serde_derive = "1.0.133"
home = "0.5.3"
