seperator = " "

[[module]]
prefix = " "
command = "uname -r"

[[module]]
prefix = "華 "
built_in = "load"

[[module]]
prefix = " "
built_in = "time"

[[module]]
prefix = " "
built_in = "uptime"

[[module]]
prefix = " "
built_in = "cpu"

[[module]]
prefix = " "
built_in = "mem"
