modules = ["kernel", "load", "time", "uptime", "cpu", "mem"]
seperator = " "

[module."kernel"]
prefix = " "
command = "uname -r"

[module."load"]
prefix = "華 "

[module."time"]
prefix = " "

[module."uptime"]
prefix = " "

[module."cpu"]
prefix = " "

[module."mem"]
prefix = " "
